### ISSUE TITLE
Error with osm_consolidate

### ISSUE THREAD

**Issue by Robinlovelace** [saferactive/traffiCalmr#45]
Heads-up @mem48 there is an error when I run this function:

(Heads-up also @joeytalbot sorry for being slow on this!)

```
region_name = "Isle of Wight"
> # region_name = "Greater London" # test for London
> osm = osmextract::oe_get(region_name)
> osm = osm_main_roads(osm)
> osm = sf::st_transform(osm, 27700)
> osm = osm_consolidate(osm)
 Error in `[.data.frame`(x, i, j, drop = drop) : 
  undefined columns selected 
```

**Comment by mem48** [comment]
You need the correct osm tags, see the example

**Comment by Robinlovelace** [comment]
Fixed in https://github.com/saferactive/trafficalmr/commit/c2fa0cbfea52b90855bcc594c3b3d29122c7f9a6 as shown above. This issue will close when we merge the PR.
